[project]
name = "tgmonopoly"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "channels-redis>=4.2.1",
    "channels[daphne]>=4.2.2",
    "django>=5.2.3",
    "django-cors-headers>=4.7.0",
    "django-extensions>=4.1",
    "django-stubs[compatible-mypy]>=5.2.1",
    "django-vite>=3.1.0",
    "djangorestframework>=3.16.0",
    "djangorestframework-stubs>=3.16.0",
    "mypy>=1.16.1",
    "pillow>=11.2.1",
    "pydantic>=2.11.7",
    "pydantic-extra-types>=2.10.5",
    "pytelegrambotapi>=4.27.0",
    "python-dotenv>=1.1.0",
    "rich>=14.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]

[tool.ruff]
# Allow lines to be as long as 120.
line-length = 110