# Generated by Django 5.2.3 on 2025-07-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='lang_code',
            new_name='language_code',
        ),
    ]
