# Generated by Django 5.2.3 on 2025-07-14 07:55

import django.core.validators
import django.db.models.deletion
import game.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0002_rename_lang_code_telegramuser_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('classic', 'Classic')], max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=32)),
                ('board_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='game.boardconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('tile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.tile')),
            ],
            bases=('game.tile',),
        ),
        migrations.CreateModel(
            name='Chance',
            fields=[
                ('tile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.tile')),
            ],
            bases=('game.tile',),
        ),
        migrations.CreateModel(
            name='Jail',
            fields=[
                ('tile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.tile')),
            ],
            bases=('game.tile',),
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('tile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.tile')),
            ],
            bases=('game.tile',),
        ),
        migrations.CreateModel(
            name='Start',
            fields=[
                ('tile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.tile')),
            ],
            bases=('game.tile',),
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('tile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.tile')),
            ],
            bases=('game.tile',),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('max_players', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2, 'Game should have more than 2 players')])),
                ('turn', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('PLAYING', 'Playing'), ('FINISHED', 'Finished'), ('ABANDONED', 'Abandoned')], default='WAITING', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('board_config', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='games', to='game.boardconfig')),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('player.joined', 'Player Joined'), ('player.action', 'Player Action'), ('player.leave', 'Player Leave'), ('player.roll_dice', 'Player Roll Dice'), ('player.move', 'Player Move'), ('game.started', 'Game Started')], max_length=32)),
                ('extra_data', models.JSONField(default=dict)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('cash', models.IntegerField(default=10)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow')], max_length=12)),
                ('rolled_double', models.BooleanField(default=False)),
                ('double_count', models.PositiveSmallIntegerField(default=0)),
                ('in_jail', models.BooleanField(default=False)),
                ('jail_turns', models.PositiveSmallIntegerField(default=0)),
                ('move_backwards', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('won', 'Won'), ('lost', 'Lost'), ('timeout', 'Timeout')], default='waiting', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='PendingAction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('roll_dice', 'Roll Dice'), ('buy_property', 'Buy Property')], max_length=32)),
                ('action_data', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pending_actions', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houses', models.IntegerField(default=0)),
                ('mortgaged', models.BooleanField(default=False)),
                ('mortage_last_turn', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='game.game')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='game.tile')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to='game.player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_player', to='game.player'),
        ),
        migrations.CreateModel(
            name='PropertyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=32, validators=[game.utils.validate_color])),
                ('board_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_groups', to='game.boardconfig')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('UTILITY_1', 'Utility 1'), ('UTILITY_2', 'Utility 2')], max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=32, validators=[game.utils.validate_color])),
                ('board_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_groups', to='game.boardconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('tile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.tile')),
                ('price', models.PositiveSmallIntegerField()),
                ('mortgage_value', models.PositiveSmallIntegerField()),
                ('house_price', models.PositiveSmallIntegerField()),
                ('rent', models.PositiveSmallIntegerField()),
                ('rent_with_1_house', models.PositiveSmallIntegerField()),
                ('rent_with_2_houses', models.PositiveSmallIntegerField()),
                ('rent_with_3_houses', models.PositiveSmallIntegerField()),
                ('rent_with_4_houses', models.PositiveSmallIntegerField()),
                ('rent_with_5_houses', models.PositiveSmallIntegerField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='properties')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.propertygroup')),
            ],
            bases=('game.tile',),
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('tile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.tile')),
                ('price', models.IntegerField()),
                ('mortgage_value', models.IntegerField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='properties')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.utilitygroup')),
            ],
            bases=('game.tile',),
        ),
        migrations.AddConstraint(
            model_name='tile',
            constraint=models.UniqueConstraint(fields=('board_config', 'position'), name='unique_board_config_position'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='unique_user_game'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('color', 'game'), name='unique_color_per_game'),
        ),
        migrations.AddConstraint(
            model_name='pendingaction',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('player',), name='unique_active_pending_action_per_player'),
        ),
        migrations.AddConstraint(
            model_name='ownership',
            constraint=models.UniqueConstraint(fields=('game', 'tile'), name='unique_game_tile_in_ownership'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('max_players__gte', 2)), name='max_players_gte_2'),
        ),
    ]
