# Generated by Django 5.1.1 on 2024-09-18 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('chance', 'Chance'), ('community_chest', 'Community Chest')], max_length=20)),
                ('description', models.TextField()),
                ('action', models.CharField(max_length=50)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_players', models.IntegerField(default=2)),
                ('turn', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('PLAYING', 'Playing'), ('FINISHED', 'Finished')], default='WAITING', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39)], unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('START', 'Start'), ('PROPERTY', 'Property'), ('CHANCE', 'Chance'), ('UTILITY', 'Utility'), ('UTILITY_2', 'Utility 2')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('cash', models.IntegerField(default=1500)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('in_jail', models.BooleanField(default=False)),
                ('jail_turns', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser')),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('mortgage_value', models.IntegerField()),
                ('house_price', models.IntegerField(blank=True, null=True)),
                ('rent', models.IntegerField()),
                ('rent_with_1_house', models.IntegerField()),
                ('rent_with_2_houses', models.IntegerField()),
                ('rent_with_3_houses', models.IntegerField()),
                ('rent_with_4_houses', models.IntegerField()),
                ('rent_with_5_houses', models.IntegerField()),
                ('color_group', models.CharField(blank=True, max_length=50, null=True)),
                ('board_space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.tile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_sent', to='game.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='game.game')),
                ('to_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_received', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houses', models.IntegerField(default=0)),
                ('mortgaged', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to='game.player')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.property')),
            ],
            options={
                'unique_together': {('player', 'property')},
            },
        ),
    ]
