# Generated by Django 5.1.1 on 2024-09-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='properties'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='type',
            field=models.CharField(choices=[('START', 'Start'), ('PROPERTY', 'Property'), ('CHANCE', 'Chance'), ('TAX', 'Tax'), ('UTILITY', 'Utility'), ('UTILITY_2', 'Utility 2'), ('JAIL', 'Jail'), ('CASINO', 'Casino'), ('POLICE', 'Police')], max_length=20),
        ),
    ]
