# Generated by Django 5.1.1 on 2024-09-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_propertygroup_remove_property_color_group_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('board_space', 'group')},
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('mortgage_value', models.IntegerField()),
                ('type', models.CharField(choices=[('UTILITY_1', 'Utility 1'), ('UTILITY_2', 'Utility 2')], max_length=20)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='properties')),
                ('board_space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.tile')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.propertygroup')),
            ],
            options={
                'unique_together': {('board_space', 'group')},
            },
        ),
    ]
