# Generated by Django 5.1.1 on 2024-09-22 19:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_property_unique_together_utility'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='tile',
            name='type',
            field=models.CharField(choices=[('START', 'Start'), ('PROPERTY', 'Property'), ('CHANCE', 'Chance'), ('TAX', 'Tax'), ('UTILITY', 'Utility'), ('JAIL', 'Jail'), ('CASINO', 'Casino'), ('POLICE', 'Police')], max_length=20),
        ),
    ]
