# Generated by Django 5.1.1 on 2024-09-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_gameeffect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameeffect',
            old_name='effect',
            new_name='name',
        ),
    ]
