# Generated by Django 5.1.1 on 2024-09-28 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_rename_effect_gameeffect_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_player', to='game.player'),
        ),
        migrations.AlterField(
            model_name='gameeffect',
            name='name',
            field=models.CharField(choices=[('start_game', 'Start Game'), ('roll_dice', 'Roll Dice')], max_length=20),
        ),
    ]
