# Generated by Django 5.1.1 on 2024-09-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_current_player_alter_gameeffect_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameeffect',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
