# Generated by Django 5.1.1 on 2024-10-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_gameeffect_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(blank=True, choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow')], max_length=10, null=True),
        ),
    ]
