# Generated by Django 5.1.1 on 2024-10-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_player_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameeffect',
            old_name='user',
            new_name='player',
        ),
        migrations.AlterField(
            model_name='gameeffect',
            name='name',
            field=models.CharField(choices=[('start_game', 'Start Game'), ('roll_dice', 'Roll Dice'), ('ask_buy', 'Ask Buy'), ('pay_rent', 'Pay Rent')], max_length=20),
        ),
    ]
