# Generated by Django 5.1.1 on 2024-10-04 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_rename_user_gameeffect_player_alter_gameeffect_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='game.game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameeffect',
            name='name',
            field=models.CharField(choices=[('roll_dice', 'Roll Dice'), ('ask_buy', 'Ask Buy'), ('pay_rent', 'Pay Rent')], max_length=20),
        ),
    ]
