# Generated by Django 5.1.1 on 2024-10-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_ownership_game_alter_gameeffect_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameeffect',
            name='effect_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
