# Generated by Django 5.1.1 on 2024-10-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_gameeffect_effect_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('won', 'Won'), ('lost', 'Lost')], default='waiting', max_length=16),
        ),
    ]
