# Generated by Django 5.1.1 on 2024-10-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_player_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameeffect',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('won', 'Won'), ('lost', 'Lost'), ('timeout', 'Timeout')], default='waiting', max_length=16),
        ),
    ]
