# Generated by Django 5.1.1 on 2024-10-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_gameeffect_task_id_alter_player_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='mortage_last_turn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
