# Generated by Django 5.1.1 on 2024-10-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_ownership_mortage_last_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='move_backwards',
            field=models.BooleanField(default=False),
        ),
    ]
