# Generated by Django 5.1.1 on 2024-10-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_chancecard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chancecard',
            name='action',
        ),
        migrations.RemoveField(
            model_name='chancecard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chancecard',
            name='value',
        ),
        migrations.AddField(
            model_name='chancecard',
            name='card_type',
            field=models.CharField(choices=[('MOVE', 'Move'), ('MOVE_BACKWARDS', 'Move Backwards'), ('MONEY', 'Money'), ('JAIL', 'Go to Jail'), ('FREE_JAIL', 'Get Out of Jail Free'), ('REPAIRS', 'Repairs'), ('MISC', 'Miscellaneous')], default='MOVE_BACKWARDS', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chancecard',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chancecard',
            name='title',
            field=models.CharField(default='MOVE_BACKWARDS', max_length=100),
            preserve_default=False,
        ),
    ]
