# Generated by Django 5.1.1 on 2024-10-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_remove_chancecard_action_remove_chancecard_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('UTILITY', 'Utility'), ('PROPERTY', 'Property')], default='PROPERTY', max_length=10),
        ),
        migrations.AlterField(
            model_name='chancecard',
            name='card_type',
            field=models.CharField(choices=[('MOVE', 'Move'), ('MOVE_BACKWARDS', 'Move Backwards'), ('MONEY', 'Money'), ('MONEY_TO_PLAYER', 'Money to Player'), ('GO_TO_JAIL', 'Go to Jail'), ('FREE_JAIL', 'Get Out of Jail Free'), ('REPAIRS', 'Repairs'), ('MISC', 'Miscellaneous')], max_length=16),
        ),
        migrations.AlterField(
            model_name='gameeffect',
            name='name',
            field=models.CharField(choices=[('roll_dice', 'Roll Dice'), ('ask_buy', 'Ask Buy'), ('pay_rent', 'Pay Rent'), ('pay_repairs', 'Pay Repairs')], max_length=20),
        ),
    ]
