# Generated by Django 5.1.1 on 2024-10-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_remove_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='svg_icon',
            field=models.CharField(blank=True, choices=[('WIND_POWER', 'Wind Power')], max_length=50, null=True),
        ),
    ]
