# Generated by Django 5.1.1 on 2024-11-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_property_svg_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameeffect',
            name='name',
            field=models.CharField(choices=[('roll_dice', 'Roll Dice'), ('ask_buy', 'Ask Buy'), ('pay_rent', 'Pay Rent'), ('pay_repairs', 'Pay Repairs'), ('in_casino', 'In Casino')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='svg_icon',
            field=models.CharField(blank=True, choices=[('WIND_POWER', 'Wind Power'), ('DAM', 'Dam'), ('SOLAR_POWER', 'Solar Power'), ('NUKE', 'Nuke')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertygroup',
            name='name',
            field=models.CharField(choices=[('UTILITIES_1', 'Utilities 1'), ('UTILITIES_2', 'Utilities 2'), ('TECH', 'Tech'), ('FINANCE', 'Finance'), ('MEDECINE', 'Medecine'), ('OIL', 'Oil'), ('AUTOMOBILE', 'Automobile'), ('COMMUNICATION', 'Communication'), ('FOOD', 'Food'), ('CLOTH', 'Cloth')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together={('game', 'property')},
        ),
    ]
