# Generated by Django 5.1.1 on 2025-01-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_alter_gameeffect_name_alter_property_svg_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dobule_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='rolled_double',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameeffect',
            name='name',
            field=models.CharField(choices=[('roll_dice', 'Roll Dice'), ('ask_buy', 'Ask Buy'), ('pay_rent', 'Pay Rent'), ('pay_repairs', 'Pay Repairs'), ('in_casino', 'In Casino'), ('in_trade', 'In Trade'), ('in_auction', 'In Auction')], max_length=20),
        ),
    ]
