# Generated by Django 5.1.1 on 2025-02-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_player_dobule_count_player_rolled_double_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chancecard',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('PLAYING', 'Playing'), ('FINISHED', 'Finished'), ('ABANDONED', 'Abandoned')], default='WAITING', max_length=16),
        ),
        migrations.AlterField(
            model_name='gameeffect',
            name='name',
            field=models.CharField(choices=[('roll_dice', 'Roll Dice'), ('ask_buy', 'Ask Buy'), ('pay_rent', 'Pay Rent'), ('pay_repairs', 'Pay Repairs'), ('pay_bank', 'Pay Bank'), ('in_casino', 'In Casino'), ('in_trade', 'In Trade'), ('in_auction', 'In Auction')], max_length=20),
        ),
    ]
