export const DICE_ANIMATION_DURATION_SECONDS = 1;
// export const DICE_SHOW_DURATION_SECONDS = 1;
// export const DICE_SHOW_DURATION_SECONDS_TOTAL_SECONDS =
//   DICE_ANIMATION_DURATION_SECONDS + DICE_SHOW_DURATION_SECONDS;
export const PLAYER_CHIP_MOVE_DURATION_MS = 500;
export const PLAYER_CHIP_COLORS = {
  // primary, border
  blue: ["#3366FF", "#003366"],
  red: ["#d11919", "#660000"],
  green: ["#36d119", "#006600"],
  yellow: ["#ebda1e", "#ad9f03"],
};
export const CASH_LOSS_ANIMATION_DURATION_SECONDS = 3;
export const CASH_GAIN_ANIMATION_DURATION_SECONDS = 2;
export const MAXIMUM_JAIL_TURNS = 3;
export const PRISON_PAY_AMOUNT = 50;
export const COIN_FLIP_ANIMATION_DURATION_MS = 2000;
export const COIN_FLIP_RESULT_DURATION_MS = 1000;
export const WEBSOCKET_RECONNECT_DELAY = 1000 * 1;
