export const DICE_ANIMATION_DURATION_SECONDS = 1;
// export const DICE_SHOW_DURATION_SECONDS = 1;
// export const DICE_SHOW_DURATION_SECONDS_TOTAL_SECONDS =
//   DICE_ANIMATION_DURATION_SECONDS + DICE_SHOW_DURATION_SECONDS;
export const PLAYER_CHIP_MOVE_DURATION_MS = 300;
